export const menuColors: MenuThemeColors = {
  cartScreenBgColor: '#DCDCDC',
  cartScreenCartErrorTextColor: '#E8060D',
  cartScreenCartItemDeleteBtnColor: '#DCDCDC',
  cartScreenCartItemDeleteBtnTextColor: '#1C1C1C',
  cartScreenCartItemPriceTextColor: 'rgba(0, 32, 82, 1)',
  cartScreenCartItemTitleTextColor: '#1C1C1C',
  cartScreenCartItemVariationTextColor: 'rgba(0, 32, 82, 1)',
  cartScreenCartQtyDropdownBtnColor: '#DCDCDC',
  cartScreenCartQtyDropdownBtnDropdownTextColor: '#1C1C1C',
  cartScreenCartQtyDropdownBtnSelectedTextColor: 'rgba(0, 32, 82, 1)',
  cartScreenCartSubtotalTextColor: 'rgba(0, 32, 82, 1)',
  cartScreenCartSuccessTextColor: '#22C201',
  cartScreenCartTotalAmountTextColor: '#FE2472',
  cartScreenContinueShoppingBtnColor: 'rgba(0, 32, 82, 1)',
  cartScreenContinueShoppingBtnTextColor: '#FFFFFF',
  cartScreenFormDefaultBtnColor: 'rgba(0, 32, 82, 1)',
  cartScreenFormDefaultBtnTextColor: '#FFFFFF',
  cartScreenFormInputBorderColor: 'rgba(0, 32, 82, 1)',
  cartScreenFormInputPlaceholderTextColor: '#1C1C1C',
  cartScreenFormInputTextColor: '#1C1C1C',
  cartScreenSubmitOrderBtnColor: 'rgba(0, 32, 82, 1)',
  cartScreenSubmitOrderBtnTextColor: '#FFFFFF',
  categoryScreenBgColor: '#DCDCDC',
  categoryScreenProductAddToCardIconColor: 'rgba(0, 32, 82, 1)',
  categoryScreenProductBgColor: 'rgba(248, 247, 241, 1)',
  categoryScreenProductDiscountPriceTextColor: 'rgba(172, 172, 172, 1)',
  categoryScreenProductDiscountTextColor: 'rgba(172, 172, 172, 1)',
  categoryScreenProductPriceTextColor: 'rgba(172, 172, 172, 1)',
  categoryScreenProductSmallDescriptionTextColor: '#1C1C1C',
  categoryScreenProductTitleTextColor: 'rgba(0, 32, 82, 1)',
  drawerBgColor: 'rgba(255, 204, 0, 1)',
  drawerListItemBgColor: '#DCDCDC',
  drawerListItemSelectedBgColor: 'rgba(0, 32, 82, 1)',
  drawerListItemSelectedTextColor: 'rgba(255, 204, 0, 1)',
  drawerListItemTextColor: 'rgba(0, 32, 82, 1)',
  feedbackHeaderTextColor: 'rgba(0, 32, 82, 1)',
  feedbackParagraphTextColor: 'rgba(0, 32, 82, 1)',
  feedbackSubmitBtnColor: 'rgba(0, 32, 82, 1)',
  feedbackSubmitBtnTextColor: '#FFFFFF',
  feedbackSuccessTextColor: 'rgba(50, 205, 0, 1)',
  headerBgColor: 'rgba(0, 32, 82, 1)',
  headerCartIconColor: 'rgba(255, 204, 0, 1)',
  headerCartNotifyColor: '#FE2472',
  headerMenuIconColor: 'rgba(255, 204, 0, 1)',
  headerSearchIconColor: 'rgba(255, 204, 0, 1)',
  headerTitleTextColor: 'rgba(255, 204, 0, 1)',
  headerMenuClosedBgColor: '#E8060D',
  headerMenuClosedTextColor: '#FFFFFF',
  homeScreenBgColor: '#DCDCDC',
  homeScreenCategoryBgColor: 'rgba(255, 204, 0, 1)',
  homeScreenCategoryTitleTextColor: 'rgba(0, 32, 82, 1)',
  onboardingScreenBgColor: '#DCDCDC',
  onboardingScreenIconColor: 'rgba(0, 32, 82, 1)',
  onboardingScreenOpenMenuButtonColor: 'rgba(0, 32, 82, 1)',
  onboardingScreenOpenMenuTextColor: 'rgba(255, 204, 0, 1)',
  onboardingScreenTitleTextColor: 'rgba(220, 220, 220, 0)',
  productScreenAddToCartBtnColor: 'rgba(0, 32, 82, 1)',
  productScreenAddToCartTextColor: 'rgba(255, 204, 0, 1)',
  productScreenArrowColor: 'rgba(0, 32, 82, 1)',
  productScreenBgColor: 'rgba(233, 233, 233, 1)',
  productScreenDescriptionBgColor: '#FFFFFF',
  productScreenProductDescriptionTextColor: 'rgba(0, 32, 82, 1)',
  productScreenProductDiscountPriceTextColor: 'rgba(255, 0, 0, 1)',
  productScreenProductDiscountTextColor: 'rgba(23, 211, 56, 1)',
  productScreenProductNameTextColor: 'rgba(0, 32, 82, 1)',
  productScreenProductPriceTextColor: 'rgba(172, 172, 172, 1)',
  productScreenPropertyBgColor: '#6c757d',
  productScreenPropertyTextColor: '#FFFFFF',
  productScreenVariationDropdownBtnColor: '#DCDCDC',
  productScreenVariationDropdownBtnDropdownTextColor: '#1C1C1C',
  productScreenVariationDropdownBtnSelectedTextColor: 'rgba(0, 32, 82, 1)',
  productScreenVariationDropdownTitleTextColor: '#1C1C1C',
};

export const menuFontSize: MenuThemeFontSize = {
  cartScreenCartErrorFontSize: 18,
  cartScreenCartItemDeleteBtnFontSize: 12,
  cartScreenCartItemPriceFontSize: 16,
  cartScreenCartItemTitleFontSize: 18,
  cartScreenCartItemVariationFontSize: 18,
  cartScreenCartQtyDropdownBtnDropdownFontSize: 16,
  cartScreenCartQtyDropdownBtnSelectedFontSize: 16,
  cartScreenCartSubtotalFontSize: 20,
  cartScreenCartSuccessFontSize: 18,
  cartScreenContinueShoppingBtnFontSize: 16,
  cartScreenFormDefaultBtnFontSize: 16,
  cartScreenSubmitOrderBtnFontSize: 18,
  categoryScreenProductDiscountFontSize: 14,
  categoryScreenProductDiscountPriceFontSize: 14,
  categoryScreenProductPriceFontSize: 14,
  categoryScreenProductSmallDescriptionFontSize: 13,
  categoryScreenProductTitleFontSize: 14,
  drawerListItemFontSize: 16,
  drawerListItemSelectedFontSize: 18,
  feedbackParagraphFontSize: 20,
  feedbackSubmitBtnFontSize: 18,
  feedbackSuccessFontSize: 18,
  headerTitleFontSize: 18,
  homeScreenCategoryTitleFontSize: 18,
  onboardingScreenOpenMenuFontSize: 18,
  onboardingScreenTitleFontSize: 20,
  productScreenAddToCartFontSize: 16,
  productScreenProductDescriptionFontSize: 16,
  productScreenProductDiscountFontSize: 16,
  productScreenProductDiscountPriceFontSize: 16,
  productScreenProductNameFontSize: 24,
  productScreenProductPriceFontSize: 16,
  productScreenPropertyFontSize: 10,
  productScreenVariationDropdownBtnDropdownFontSize: 16,
  productScreenVariationDropdownBtnSelectedFontSize: 16,
  productScreenVariationDropdownTitleFontSize: 16,
  headerMenuClosedFontSize: 16,
};

export const menuFontFamily: MenuThemeFontFamily = {
  cartScreenCartErrorFontFamily: 'Gill-Sans-Regular',
  cartScreenCartItemDeleteBtnFontFamily: 'Gill-Sans-Regular',
  cartScreenCartItemPriceFontFamily: 'Gill-Sans-Regular',
  cartScreenCartItemTitleFontFamily: 'Gill-Sans-Regular',
  cartScreenCartItemVariationFontFamily: 'Gill-Sans-Regular',
  cartScreenCartQtyDropdownBtnDropdownFontFamily: 'Gill-Sans-Regular',
  cartScreenCartQtyDropdownBtnSelectedFontFamily: 'Gill-Sans-Regular',
  cartScreenCartSubtotalFontFamily: 'Gill-Sans-Regular',
  cartScreenCartSuccessFontFamily: 'Gill-Sans-Regular',
  cartScreenContinueShoppingBtnFontFamily: 'Gill-Sans-Regular',
  cartScreenFormDefaultBtnFontFamily: 'Gill-Sans-Regular',
  cartScreenSubmitOrderBtnFontFamily: 'Gill-Sans-Regular',
  categoryScreenProductDiscountFontFamily: 'Oswald-Regular',
  categoryScreenProductDiscountPriceFontFamily: 'Oswald-Regular',
  categoryScreenProductPriceFontFamily: 'Oswald-Regular',
  categoryScreenProductSmallDescriptionFontFamily: 'Gill-Sans-Regular',
  categoryScreenProductTitleFontFamily: 'Gill-Sans-Regular',
  drawerListItemFontFamily: 'Gill-Sans-Regular',
  drawerListItemSelectedFontFamily: 'Gill-Sans-Regular',
  feedbackHeaderFontFamily: 'Gill-Sans-Regular',
  feedbackParagraphFontFamily: 'Comfortaa-Bold',
  feedbackSubmitBtnFontFamily: 'Gill-Sans-Regular',
  feedbackSuccessFontFamily: 'Gill-Sans-Regular',
  headerTitleFontFamily: 'Gill-Sans-Regular',
  homeScreenCategoryTitleFontFamily: 'Gill-Sans-Regular',
  onboardingScreenOpenMenuFontFamily: 'Gill-Sans-Regular',
  onboardingScreenTitleFontFamily: 'Gill-Sans-Regular',
  productScreenAddToCartFontFamily: 'Gill-Sans-Regular',
  productScreenProductDescriptionFontFamily: 'Gill-Sans-Regular',
  productScreenProductDiscountFontFamily: 'Oswald-Regular',
  productScreenProductDiscountPriceFontFamily: 'Oswald-Regular',
  productScreenProductNameFontFamily: 'Gill-Sans-Regular',
  productScreenProductPriceFontFamily: 'Oswald-Regular',
  productScreenPropertyFontFamily: 'Gill-Sans-Regular',
  productScreenVariationDropdownBtnDropdownFontFamily: 'Gill-Sans-Regular',
  productScreenVariationDropdownBtnSelectedFontFamily: 'Gill-Sans-Regular',
  productScreenVariationDropdownTitleFontFamily: 'Gill-Sans-Regular',
  headerMenuClosedFontFamily: 'Gill Sans MT',
};
